### PR TITLE
Foundation Security blackduck scans

### PR DESCRIPTION
**Pull request by OliverRiggs**
New workflow that triggers on Tag

### CODE REVIEW

**Comment by OliverRiggs** [comment]
Please review @edbjunwang

**Comment by edbjunwang** [comment]
Hi @OliverRiggs As we discussed yesterday, could you submit the PR/workflow to https://github.com/EnterpriseDB/sslutils-packaging?

**Comment by edbjunwang** [comment]
Hi @OliverRiggs The PR looks fine to me

**Comment by OliverRiggs** [comment]
These public repo changes need to be reworked

**Pull request closed without merging**
